trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  javaVersion: '11'
  nodeVersion: '14.x'
  workingDirectory: '$(Build.SourcesDirectory)'

stages:
- stage: Build
  displayName: 'Build and Test'
  jobs:
  - job: BuildBackend
    displayName: 'Build and Test Backend'
    steps:
    - checkout: self
    - task: UseJavaVersion@1
      inputs:
        version: $(javaVersion)
        jdkArchitecture: 'x64'
    - script: |
        cd $(workingDirectory)/src
        mvn clean package -DskipTests
      displayName: 'Maven Build'

  - job: BuildFrontend
    displayName: 'Build Frontend'
    steps:
    - checkout: self
    - task: NodeTool@0
      inputs:
        versionSpec: $(nodeVersion)
    - script: |
        cd $(workingDirectory)/client
        npm install
        npm run build -- --prod
      displayName: 'Build Angular App'

- stage: Deploy
  displayName: 'Deploy to Azure'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
  - deployment: DeployApp
    displayName: 'Deploy App'
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: AzureWebApp@1
            inputs:
              appName: 'YourSpringBootAppName'
              package: $(workingDirectory)/src/target/*.jar
              runtimeStack: 'JAVA|11-java11'
          - task: AzureWebApp@1
            inputs:
              appName: 'YourAngularAppName'
              package: $(workingDirectory)/client/dist/client
