trigger:
- main

pool:
  vmImage: 'Ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: BuildApplication
    displayName: 'Build Java Application and Docker Image'
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'BusinessMapping/pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.21'
        jdkArchitectureOption: 'x64'
        goals: 'package'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'

- stage: SetupNode
  jobs:
  - job: SetupNodeJs
    displayName: 'Install Node.js and Build Angular Application'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '21.5.0'
        checkLatest: true
      displayName: 'Install Node.js'

    - script: |
        cd BusinessMapping/client
        npm install
        npm run build -- --configuration production
      displayName: 'Build Angular Application'
