# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- bash: 'wget --no-check-certificate -c --header "Cookie: oraclelicense=accept-securebackup-cookie" https://download.oracle.com/java/21/latest/jdk-21_linux-x64_bin.tar.gz '
  displayName: 'Bash Script'

- task: DockerInstaller@0
  displayName: "Install Docker"
  inputs:
    dockerVersion: '17.09.0-ce'

- script: |
    docker pull neo4j:latest
    docker run -d --name neo4j -p 7474:7474 -p 7687:7687 -e NEO4J_AUTH=neo4j/test neo4j:latest
  displayName: 'Start Neo4j Docker Container'

- script: |
    echo "Run your tests or other pipeline tasks that need Neo4j here."
  displayName: 'Run Tests'

- script: |
    docker stop neo4j
    docker rm neo4j
  displayName: 'Stop and Remove Neo4j Docker Container'
- task: JavaToolInstaller@0
  displayName: 'Use Java 21'
  inputs:
    versionSpec: 21
    jdkArchitectureOption: x64
    jdkSourceOption: LocalDirectory
    jdkFile: '$(build.sourcesdirectory)/jdk-21_linux-x64_bin.tar.gz'
    jdkDestinationDirectory: '$(agent.toolsDirectory)/jdk21'
- task: Maven@3
  inputs:
    mavenPomFile: 'BusinessMapping/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.21'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '21.5.0'
  displayName: 'Install Node.js'

- script: |
    cd BusinessMapping/client
    npm install
    npm run build -- --configuration production
  displayName: 'Build Angular Application'

