trigger:
- main

pool:
  vmImage: 'Ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: BuildApplication
    displayName: 'Build Java Application and Docker Image'
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'BusinessMapping/pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.21'
        jdkArchitectureOption: 'x64'
        goals: 'package'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'

    - task: DockerInstaller@0
      displayName: "Install Docker"
      inputs:
        dockerVersion: '17.09.0-ce'

    - script: |
        docker pull neo4j:latest
        docker run -d --name neo4j -p 7474:7474 -p 7687:7687 -e NEO4J_AUTH=neo4j/test neo4j:latest
      displayName: 'Start Neo4j Docker Container'

- stage: Deploy
  jobs:
  - deployment: DeployWeb
    displayName: 'Deploy Web App'
    environment: 
      name: 'production'
      resourceName: ip-172-31-28-179
      resourceType: virtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Hello world

- stage: SetupNode
  jobs:
  - job: SetupNodeJs
    displayName: 'Install Node.js and Build Angular Application'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '21.5.0'
        checkLatest: true
      displayName: 'Install Node.js'

    - script: |
        cd BusinessMapping/client
        npm install
        npm run build -- --configuration production
      displayName: 'Build Angular Application'

- stage: DeployApp
  jobs:
  - job: DeployAngularApp
    displayName: 'Deploy Angular Application'
    steps:
    - script: |
        sudo apt-get update
        sudo apt-get install -y nginx
      displayName: 'Install Nginx'

    - script: |
        sudo rm -rf /usr/share/nginx/html/*
        sudo cp -r BusinessMapping/BusinessMapping/client/dist/client/* /usr/share/nginx/html/
      displayName: 'Copy Angular App to Nginx'

    - script: |
        sudo systemctl restart nginx
      displayName: 'Restart Nginx'